### ISSUE TITLE
Issue with fork ?

### ISSUE THREAD

**Issue by nits01** [VAR-solutions/Algorithms#1175] opened 2020-10-01 08:13 UTC
I am trying to clone this repo after forking but its giving me errors.

**Comment by i-vishi** [comment] 2020-10-01 08:58
@nits01 can you try again?

**Comment by i-vishi** [comment] 2020-10-01 09:32
Is anyone having issues while forking this repo?

**Comment by i-vishi** [comment] 2020-10-01 10:23
The issue is fixed. I am closing this issue

**Closed by i-vishi** 2020-10-01 10:23 UTC
Labels: fixed
